apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: platform
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.96.0
          args: ["--config=/conf/config.yaml"]
          env:
            - name: LOG_RETENTION_DAYS
              value: "7"           # change N here or override via values
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
        - name: varlogpods
          hostPath:
            path: /var/lib/docker/volumes/minikube/_data/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/volumes/minikube/_data/lib/docker/containers
